###
curl -j -b /tmp/cookie-jar.txt -c /tmp/cookie-jar.txt -X PUT --location "http://localhost:8080/wallet" \
    -H "Content-Type: application/json" \
    -d "{
          \"network\": \"testnet\",
          \"descriptor\": \"wpkh([1f44db3b/84'/1'/0'/0]tpubDEtS2joSaGheeVGuopWunPzqi7D3BJ9kooggvasZWUzSVziMNKkrdfS7VnLDe6M4Cg6bw3j5oxRB5U7GMJGcFnDia6yUaFAdwWqyJQjn4Qp/0/*)\"
        }"
###
PUT http://localhost:8080/wallet
Content-Type: application/json

{
  "network": "testnet",
  "descriptor": "wpkh([1f44db3b/84'/1'/0'/0]tpubDEtS2joSaGheeVGuopWunPzqi7D3BJ9kooggvasZWUzSVziMNKkrdfS7VnLDe6M4Cg6bw3j5oxRB5U7GMJGcFnDia6yUaFAdwWqyJQjn4Qp/0/*)"
}

###
curl -b /tmp/cookie-jar.txt -c /tmp/cookie-jar.txt -X DELETE --location "http://localhost:8080/wallet"
###
DELETE http://localhost:8080/wallet

###
curl -b /tmp/cookie-jar.txt -X GET --location "http://localhost:8080/wallet/balance"
###
GET http://localhost:8080/wallet/balance

###
curl -b /tmp/cookie-jar.txt -X GET --location "http://localhost:8080/wallet/address/new"
###
GET http://localhost:8080/wallet/address/new

###
curl -b /tmp/cookie-jar.txt -X GET --location "http://localhost:8080/wallet/transactions"
###
GET http://localhost:8080/wallet/transactions

###
GET http://localhost:8080/wallet/transaction?recipient=tb1ql7w62elx9ucw4pj5lgw4l028hmuw80sndtntxt&amount=1000&fee_rate=4

###
PUT http://localhost:8080/wallet/broadcast
Content-Type: text/plain

cHNidP8BAHEBAAAAAWsTxYHb4MYlZeJbAQVW2sBrwzyOOK5YXbLWrkEaQ7+7AAAAAAD/////AugDAAAAAAAAFgAU/52lZ+YvMOqGVPodX71HvvjjvhP0IAAAAAAAABYAFOKP71Tl4spoI+OqwZLouAJi+rvIAAAAAAABAN4CAAAAAAEBzqfUsof1fBw0Y/4oTH4gpHvjmQGXByJ7wvGd5uSGbUcAAAAAAP7///8CECcAAAAAAAAWABS15fzJBJ9QSOi8T7Cw/sYESQrtz92KtHAIAAAAFgAUtnkjEuNWKkKkn9f61r6xNi5Gu90CRzBEAiBB7u82mOv1gvrGelV72SvXgrn0i5GjDsMgc+O/NAuwdQIgD94aIrKKc3janA+0wmxsb2ufN/Fg/KbR7uceFCy5SPwBIQK9woNPM8s1OGFnBzaFvOhnDD/8gMFT2Clch1Uv/rsuvi3+IAABAR8QJwAAAAAAABYAFLXl/MkEn1BI6LxPsLD+xgRJCu3PIgYDcHK1JoKqLx/91T86Xm21FPVApxz/KQ3VoS6Esz/7Q/IcH0TbO1QAAIABAACAAAAAgAAAAAAAAAAAAAAAAAAAIgICoILVt0+PGEmZM2CQmmDBzRx9DxsEqBvFXLHwsevY+xkcH0TbO1QAAIABAACAAAAAgAAAAAAAAAAABQAAAAA=
















